---
- name: create user for services
  user:
    name: "{{ user_name }}"
    password: "{{ start_passwd }}"
    uid: "{{ user_id }}"
    create_home: true
    generate_ssh_key: yes
    ssh_key_bits: "{{ key_option }}"
    ssh_key_file: .ssh/id_rsa
# tasks file for user
