---
- name: create dir for config for user
  file:
    path: "/home/{{ user_name }}/.kube"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: test
  debug: msg="{{ hostvars.master1.ansible_host}}"

- name: init claster
  shell: "kubeadm init --apiserver-advertise-address {{ master_ip }} --pod-network-cidr {{ pod_net }} --service-cidr {{ service_net }} --token {{ start_token }}"

- name: copy config for k8s
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ user_name }}/.kube/config"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode:  '0755'
    remote_src: yes
# tasks file for master_k8s
